name: Automated Flake Input Updates
on:
  schedule:
    # * Update every third day - might require tweaks in the future
    - cron:  '30 2 1/3 * *'

jobs:
  flake-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Update Flake
        uses: cachix/install-nix-action@v18
      - run: nix flake update

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions