name: Automated Flake Input Updates
on: [push]
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Repository
    - uses: actions/checkout@v3

    - name: Update Flake
    - uses: cachix/install-nix-action@v18
    - run: nix flake update

    - name: Commit changes
    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions